site_name: Harnice
site_url: https://harnice.github.io/Harnice/
theme:
  name: material
  font:
    text: Inter
    code: Red Hat Mono
  features:
    - navigation.footer
    - content.code.copy
  palette:
    #Â Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: black
      accent: red

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: black
      accent: red

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - md_in_html
  - pymdownx.blocks.caption

plugins:
  - include-markdown

copyright: Copyright &copy; 2025 Kenyon Shutt

nav:
  - Home: index.md

  - Getting Started:
      - Installation: getting_started/_installation.md
      - The Basics: getting_started/_the_basics.md
      - Data Structures: getting_started/_data_structures.md
      - Libraries: getting_started/_libraries.md
      - Git Integration: getting_started/_git_integration.md

  - Products:
      - Harnesses: products/_harness.md
      - Systems: products/_system.md
      - Devices: products/_device.md
      - Disconnects: products/_disconnect.md
      - Macros: products/_macro.md
      - Channel Types: products/_channel_type.md
      - Cables: products/_cable.md
      - Flagnotes: products/_flagnote.md
      - Parts: products/_part.md
      - Titleblocks: products/_titleblock.md

  - Commands:
    - Harnice Libraries: commands/_library_utils.md
    - Manipulating Circuits: commands/_circuits_utils.md
    - Feature Tree Utilities: commands/_feature_tree_utils.md
    - Formboard Utilities: commands/_formboard_utils.md
    - Working with Harnice Notes: commands/_note_utils.md
    - System Utilities: commands/_system_utils.md
    - Appearance Utilities: commands/_appearance.md
    - SVG Utilities: commands/_svg_utils.md

  - Interacting with Data:
    - Channel Maps: interacting_with_data/_channel_maps.md
    - Circuits Lists: interacting_with_data/_circuits_lists.md
    - Disconnect Maps: interacting_with_data/_disconnect_maps.md
    - Formboard Graphs: interacting_with_data/_formboard_graphs.md
    - Instances Lists: interacting_with_data/_instances_lists.md
    - Library History: interacting_with_data/_library_history.md
    - Netlists: interacting_with_data/_netlists.md
    - Post-Harness Instances Lists: interacting_with_data/_post_harness_instances_lists.md
    - Revision History Lists: interacting_with_data/_revision_history_lists.md
    - Signals Lists: interacting_with_data/_signals_lists.md
    - System Manifests: interacting_with_data/_system_manifests.md

  - Macros: macros.md