site_name: Harnice
site_url: https://harnice.github.io/Harnice/
theme:
  name: material
  font:
    text: Inter
    code: Red Hat Mono
  features:
    - navigation.footer
  palette:
    #Â Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: black
      accent: red

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: black
      accent: red

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details

copyright: Copyright &copy; 2025 Kenyon Shutt

nav:
  - Home: index.md

  - Getting Started:
      - Installation: getting_started/installation.md
      - File Structure: getting_started/index.md
      - Part Numbering and Revisioning: getting_started/index.md
      - Git Integration: getting_started/index.md

  - Products:
      - Cables: products/cable.md
      - Channel Types: products/channel_type.md
      - Devices: products/device.md
      - Disconnects: products/disconnect.md
      - Flagnotes: products/flagnote.md
      - Harnesses: products/harness.md
      - Macros: products/macro.md
      - Parts: products/part.md
      - Systems: products/system.md
      - Titleblocks: products/titleblock.md

  - Commands:

    - Directly Interacting with Data:
      - Channel Maps: commands/index.md
      - Circuits Lists: commands/index.md
      - Disconnect Maps: commands/index.md
      - Formboard Graphs: commands/index.md
      - Instances Lists: commands/index.md
      - System Manifests: commands/index.md
      - Netlists: commands/index.md
      - Post Harness Instances Lists: commands/index.md
      - Revision History Lists: commands/index.md
      - Signals Lists: commands/index.md

    - Higher Level Utilities:
      - Working with Harnice Libraries: commands/index.md
      - Manipulating Circuits: commands/index.md
      - Feature Tree Utilities: commands/index.md
      - Formboard Utilities: commands/index.md
      - Working with Harnice Notes: commands/index.md
      - System Utilities: commands/index.md
      - Appearance Utilities: commands/index.md
      - SVG Utilities: commands/index.md